# Generated by Django 2.1.15 on 2020-04-06 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 19, 39, 51, 11808), verbose_name='date played'),
        ),
    ]
