# Generated by Django 2.1.15 on 2020-04-07 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200407_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 7, 3, 22, 39, 883199), verbose_name='date played'),
        ),
    ]
