# Generated by Django 2.1.15 on 2020-04-07 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200406_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 7, 1, 58, 45, 962549), verbose_name='date played'),
        ),
    ]
