# Generated by Django 2.1.15 on 2020-04-07 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200407_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('active_id', models.AutoField(primary_key=True, serialize=False)),
                ('user1', models.CharField(default='Not Set', max_length=200)),
                ('user2', models.CharField(default='Not Set', max_length=200)),
                ('last_move', models.DateTimeField(default=datetime.datetime(2020, 4, 7, 5, 15, 43, 973979), verbose_name='last move')),
                ('active_content', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_issued',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 7, 5, 15, 43, 973979), verbose_name='date issued'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 7, 5, 15, 43, 973979), verbose_name='date played'),
        ),
    ]
