# Generated by Django 2.1.15 on 2020-04-07 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200407_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ai',
            fields=[
                ('ai_game_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='Not Set', max_length=200)),
                ('user_side', models.CharField(default='White', max_length=10)),
                ('last_move', models.DateTimeField(default=datetime.datetime(2020, 4, 7, 5, 24, 42, 659306), verbose_name='last move')),
                ('ai_content', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='active',
            name='last_move',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 7, 5, 24, 42, 659306), verbose_name='last move'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_issued',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 7, 5, 24, 42, 658281), verbose_name='date issued'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 7, 5, 24, 42, 658281), verbose_name='date played'),
        ),
    ]
