# Generated by Django 3.0.5 on 2020-04-08 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200408_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='active_fen',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_fen',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='active',
            name='active_content',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='active',
            name='last_move',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 18, 43, 16, 736796), verbose_name='last move'),
        ),
        migrations.AlterField(
            model_name='ai',
            name='last_move',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 18, 43, 16, 737818), verbose_name='last move'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_issued',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 18, 43, 16, 736796), verbose_name='date issued'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_content',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 18, 43, 16, 736796), verbose_name='date played'),
        ),
    ]
