# Generated by Django 3.0.5 on 2020-04-09 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200408_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='last_move',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 21, 55, 0, 456393), verbose_name='last move'),
        ),
        migrations.AlterField(
            model_name='ai',
            name='last_move',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 21, 55, 0, 456393), verbose_name='last move'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_issued',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 21, 55, 0, 455395), verbose_name='date issued'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 21, 55, 0, 455395), verbose_name='date played'),
        ),
    ]
