# Generated by Django 2.1.2 on 2020-04-09 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200408_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='active_fen',
            field=models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'),
        ),
        migrations.AlterField(
            model_name='active',
            name='last_move',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 3, 13, 7, 76245), verbose_name='last move'),
        ),
        migrations.AlterField(
            model_name='ai',
            name='last_move',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 3, 13, 7, 76245), verbose_name='last move'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_issued',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 3, 13, 7, 76245), verbose_name='date issued'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_fen',
            field=models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 3, 13, 7, 75245), verbose_name='date played'),
        ),
    ]
